name: First Workflow
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: 1st Job Step 1
        run: |
          echo "Hello World 1"
      - name: 1st Job Step 2
        run: |
          echo "Hello World 2"
      - name: 1st Job Step 3
        run: |
          pwd
          ls -al
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: 2nd Job Step 1
        run: |
          echo "Hello World 2"
