name: First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files
        run: |
          pwd
          ls -al
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: 2nd Job Step 1
        run: |
          pwd
          ls -al
          node --version
