name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: 1st Job Step 1
        run: |
          echo "Hello World 1"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: 2nd Job Step 1
        run: |
          echo "Hello World 2"
